[application]
name = "versualizer"
default_platform = "desktop"

[desktop]
# Window settings are configured in Rust code

[bundle]
identifier = "com.versualizer.app"
publisher = "Kevin Xiao"
icon = [
    "./icons/16x16.png",
    "./icons/24x24.png",
    "./icons/32x32.png",
    "./icons/64x64.png",
    "./icons/128x128.png",
    "./icons/128x128@2x.png",
    "./icons/icon.ico",
]
copyright = "Copyright (c) 2025 Kevin Xiao"
category = "Utility"
short_description = "A karaoke lyrics visualizer application"
long_description = "A realtime karaoke lyrics visualizer providing customizable themes and effects for singing along to music on Spotify and other platforms."

[bundle.windows]
webview_install_mode = "Skip"
